# Generated by Django 3.2.8 on 2021-10-08 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patterns', models.CharField(default='none', max_length=20)),
                ('textures', models.CharField(default='none', max_length=20)),
                ('colors', models.CharField(default='none', max_length=20)),
                ('molding', models.CharField(default='none', max_length=20)),
                ('wallpaper', models.CharField(default='none', max_length=20)),
                ('window_treatments', models.CharField(default='none', max_length=20)),
                ('rugs', models.CharField(default='none', max_length=20)),
                ('carpeting', models.CharField(default='none', max_length=20)),
                ('budget', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
