# Generated by Django 3.2.8 on 2021-10-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_questionnaire_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='wallpaper',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
